### ISSUE TITLE
Crashing on nexus 5

### ISSUE THREAD

**Issue by ils-aashishj** [ItzNotABug/HouseAds#6]
I have installed this app and it always crashing on Nexus 5 and ads are not displaying.

**Comment by ItzNotABug** [comment]
Please share the logs relating to the crash..

**Comment by ils-aashishj** [comment]
Already reported via app.

**Comment by ItzNotABug** [comment]
That issue seems to be related to the OS (6.0) itself when Toast.makeText() is called & the app uses a direct reference for `fontFamily` in its theme instead of passing it as a String..
More Info [here](https://stackoverflow.com/q/48152659/6819340)

I'll update / fix the Sample App soon..
& the Library works fine :)

**Comment by ItzNotABug** [comment]
Fixed in the latest commit ccf214cb5163302df50c25a10910d6babb810d90
Updated App is uploaded on the store, should be available in a few hours.
